[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

[[plugins]]
repo = 'rhysd/rust-doc.vim'
on_ft = 'rust'

#[[plugins]]
#repo = 'autozimu/LanguageClient-neovim'
#on_ft = 'rust'
#rev = 'binary-*-x86_64-apple-darwin'
#hook_source = '''
#    let g:LanguageClient_autoStart = 0
#    nnoremap <Leader>lcs :LanguageClientStart<CR>
#
#    let g:LanguageClient_serverCommands = {
#        \ 'rust': ['rustup', 'run', 'nightly', 'rls'],
#        \ }
#
#    noremap <silent> H :call LanguageClient_textDocument_hover()<CR>
#    noremap <silent> Z :call LanguageClient_textDocument_definition()<CR>
#    noremap <silent> R :call LanguageClient_textDocument_rename()<CR>
#    noremap <silent> S :call LanguageClient_textDocument_documentSymbol()<CR>
#'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'

# private

#[[plugins]]
#repo = '~/dev/Vim/sample.vim'
#on_ft = 'vim'
#hook_source = '''
#    let g:sample#enable_at_startup = 1
#'''
