
[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
on_ft = 'rust'
depends = ['deoplete.nvim']
hook_source = '''
    let g:deoplete#sources#rust#racer_binary = expand('~/.cargo/bin/racer')
    let g:deoplete#sources#rust#rust_source_path = expand('~/.multirust/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src')
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_i = 1
hook_source = '''
let g:deoplete#enable_at_startup = 1
source ~/.vim/rc/plugins/deoplete.rc.vim
'''

#[[plugins]]
#repo = 'kassio/neoterm'
#if = "has('nvim')"
#hook_source = '''
#let g:neoterm_position = 'vertical'
#'''
