[[plugins]]
repo = 'Shougo/dein.vim'

# colorscheme
[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'simeji/winresizer'

# filer
[[plugins]]
repo = 'cocopon/vaffle.vim'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'


[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
        \ 'colorscheme': 'wombat',
        \ }
    function! LightlineFugitive()
        return fugitive#head()
    endfunction

    function! LightlineFiletype()
      return winwidth(0) > 70 ? (&filetype !=# '' ? &filetype : 'no ft') : ''
    endfunction
'''

