export EDITOR=vim
export SHELL=zsh
export ZPLUG_HOME=$HOME/.zplug
export LANG=en_US.UTF-8
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export RUST_SOURCE_PATH="$HOME/.multirust/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src"
export PATH=$HOME/go/bin:/bin:$HOME/.local/bin:/usr/local/bin:$PATH
source ~/.cargo/env
