
[[language]]
name = "python"
language-servers = ["ruff"]
# auto-format = true
# formatter = { command = "ruff", args = ["format"] }

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "rust"

[language-server.rust-analyzer]
config = { checkOnSave = { command = "clippy" }, cargo = { allFeatures = true }}

